### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by Vr0st** [Yekta-Core/FusionCMS#4]
Whenever I install FusionCMS I have the home page that shows. The installation runs smooth on PHP 5.6 
I have enabled all the extensions required and modules as well.

The site does not show if the server is online when it is. Also, whenever I click on any link on the site it simply goes to a Error page titled 404 Not Found and "The requested URL was not found on this server."

It is running on a computer that has a static IP address.

**Comment by paulvilla** [comment]
I have the same problem

**Comment by MegaWorldServer** [comment]
404 Not Found
nginx

**Comment by Nightprince** [comment]
> 404 Not Found nginx

New repo :
https://github.com/FusionWowCMS/FusionCMS
